export const LOAD_COURSES = "LOAD_COURSES";
export const SET_CURRENT_LESSON = "SET_CURRENT_LESSON";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_CURRENT_LESSON_CONTENT = "SET_CURRENT_LESSON_CONTENT";
export const SET_EDIT_SLIDE_TRUE = "SET_EDIT_SLIDE_TRUE";
export const SET_EDIT_SLIDE_FALSE = "SET_EDIT_SLIDE_FALSE";
export const SET_PAGE_CONTENT_EDITABLE = "SET_PAGE_CONTENT_EDITABLE";